### ISSUE TITLE
Test Suite Fails: 'Record' has no attribute 'data_width'

### ISSUE THREAD

**Issue by xobs** [antmicro/usb-test-suite-testbenches#11]
Something appears to have changed upstream in Litex to cause the test suite to no longer work:

https://travis-ci.com/github/im-tomu/valentyusb/jobs/300907227

**Comment by rkapuscik** [comment]
I updated the wrappers to be compatible with latest Litex, should be working now.

**Comment by xobs** [comment]
Thanks, I can verify this fixes the test suite: https://travis-ci.com/github/im-tomu/valentyusb
